@php $editing = isset($certificate) && $certificate; $prefix = $editing ? 'cert-'.$certificate->id : 'cert-new'; @endphp
<form method="POST" action="{{ $editing ? route('dashboard.certificates.update', $certificate) : route('dashboard.certificates.store') }}" enctype="multipart/form-data" class="row g-3">@csrf @if($editing) @method('PATCH') @endif
  @foreach(['uz' => 'Nomi (UZ)', 'ru' => 'Название (RU)', 'en' => 'Name (EN)'] as $locale => $label)
    <div class="col-12 col-md-4"><label class="form-label" for="{{ $prefix }}-name-{{ $locale }}">{{ $label }} <span class="required-mark" aria-hidden="true">*</span></label><input required class="form-control" id="{{ $prefix }}-name-{{ $locale }}" name="name_{{ $locale }}" value="{{ old('name_'.$locale, $editing ? $certificate->{'name_'.$locale} : '') }}"></div>
  @endforeach
  <div class="col-12 col-md-6"><label class="form-label" for="{{ $prefix }}-number">Raqami</label><input class="form-control" id="{{ $prefix }}-number" name="number" value="{{ old('number', $editing ? $certificate->number : '') }}"></div>
  <div class="col-12 col-md-6"><label class="form-label" for="{{ $prefix }}-url">Tekshirish havolasi</label><input class="form-control" id="{{ $prefix }}-url" type="url" name="verification_url" value="{{ old('verification_url', $editing ? $certificate->verification_url : '') }}"></div>
  @foreach(['uz' => 'Bergan tashkilot (UZ)', 'ru' => 'Организация (RU)', 'en' => 'Issuer (EN)'] as $locale => $label)
    <div class="col-12 col-md-4"><label class="form-label" for="{{ $prefix }}-issuer-{{ $locale }}">{{ $label }}</label><input class="form-control" id="{{ $prefix }}-issuer-{{ $locale }}" name="issuer_{{ $locale }}" value="{{ old('issuer_'.$locale, $editing ? $certificate->{'issuer_'.$locale} : '') }}"></div>
  @endforeach
  <div class="col-6"><label class="form-label" for="{{ $prefix }}-issued">Berilgan sana</label><input class="form-control" id="{{ $prefix }}-issued" type="date" name="issued_at" value="{{ old('issued_at', $editing ? optional($certificate->issued_at)->format('Y-m-d') : '') }}"></div>
  <div class="col-6"><label class="form-label" for="{{ $prefix }}-expires">Amal qilish muddati</label><input class="form-control" id="{{ $prefix }}-expires" type="date" name="expires_at" value="{{ old('expires_at', $editing ? optional($certificate->expires_at)->format('Y-m-d') : '') }}"></div>
  @foreach(['uz' => 'Qo‘llanish sohasi (UZ)', 'ru' => 'Область (RU)', 'en' => 'Scope (EN)'] as $locale => $label)
    <div class="col-12"><label class="form-label" for="{{ $prefix }}-scope-{{ $locale }}">{{ $label }}</label><textarea class="form-control" id="{{ $prefix }}-scope-{{ $locale }}" name="scope_{{ $locale }}" rows="2">{{ old('scope_'.$locale, $editing ? $certificate->{'scope_'.$locale} : '') }}</textarea></div>
  @endforeach
  <div class="col-12"><label class="form-label" for="{{ $prefix }}-document">Tasdiqlovchi fayl</label><input class="form-control admin-file-input" id="{{ $prefix }}-document" type="file" name="document" accept=".pdf,image/*" aria-describedby="{{ $prefix }}-document-help"><span class="admin-file-help" id="{{ $prefix }}-document-help">{{ $editing && $certificate->document_path ? 'Mavjud fayl saqlanadi; almashtirish uchun yangisini tanlang.' : 'Fayl tanlanmagan. PDF yoki rasm.' }}</span></div>
  <div class="col-12"><div class="form-check"><input class="form-check-input" id="{{ $prefix }}-published" type="checkbox" name="is_published" value="1" @checked(old('is_published', $editing ? $certificate->is_published : false))><label class="form-check-label" for="{{ $prefix }}-published">Saytda e’lon qilish</label></div></div>
  <div class="col-12 d-flex flex-wrap gap-2"><button class="btn btn-primary" type="submit"><i class="bi bi-check-lg me-1" aria-hidden="true"></i>{{ $editing ? 'Yangilash' : 'Sertifikatni saqlash' }}</button>@if($editing && $certificate->document_path)<a class="btn btn-outline-secondary" href="{{ asset('storage/'.$certificate->document_path) }}" target="_blank" rel="noopener"><i class="bi bi-file-earmark-text me-1" aria-hidden="true"></i>Faylni ko‘rish</a>@endif</div>
</form>
