@extends('admin.layouts.app')
@section('title', 'Maqolalar')

@section('content')
  <header class="admin-page-header"><div><span class="admin-eyebrow"><i class="bi bi-newspaper" aria-hidden="true"></i>Kontent</span><h1 class="h3 mb-1">Maqolalar</h1><p>Uch tildagi maqolalar, mualliflik va SEO ma’lumotlarini boshqaring.</p></div><a class="btn btn-primary" href="{{ route('dashboard.articles.create') }}"><i class="bi bi-plus-lg me-2" aria-hidden="true"></i>Yangi maqola</a></header>

  <section class="admin-card" aria-labelledby="article-list-title">
    <div class="admin-card-header d-flex justify-content-between align-items-center"><h2 class="h5 mb-0" id="article-list-title">Maqolalar ro‘yxati</h2><span class="text-muted">{{ $articles->total() }} ta maqola</span></div>
    @if($articles->count())
      <div class="table-responsive d-none d-lg-block"><table class="table admin-table"><thead><tr><th>Maqola</th><th>Muallif</th><th>Sana</th><th class="text-end">Amallar</th></tr></thead><tbody>
      @foreach($articles as $article)@php $plainText=trim(strip_tags(html_entity_decode((string)$article->description_uz, ENT_QUOTES|ENT_HTML5, 'UTF-8'))); @endphp
        <tr><td><div class="d-flex align-items-center gap-3">@if($article->photo)<img class="admin-thumb" src="{{ media_url($article->photo) }}" alt="">@else<span class="admin-thumb d-grid place-items-center" aria-hidden="true"><i class="bi bi-newspaper"></i></span>@endif<div><strong>{{ $article->title_uz }}</strong><div class="small text-muted">{{ \Illuminate\Support\Str::limit($plainText, 90) ?: 'Matn kiritilmagan' }}</div></div></div></td><td>{{ $article->author_name ?: 'Ko‘rsatilmagan' }}</td><td>{{ optional($article->created_at)->format('d.m.Y') }}</td><td><div class="admin-actions"><a class="btn btn-outline-primary admin-icon-button" href="{{ route('dashboard.articles.edit',$article) }}" aria-label="{{ $article->title_uz }} maqolasini tahrirlash"><i class="bi bi-pencil" aria-hidden="true"></i></a><form id="delete-article-{{ $article->id }}" method="POST" action="{{ route('dashboard.articles.destroy',$article) }}">@csrf @method('DELETE')</form><button class="btn btn-outline-danger admin-icon-button" type="button" data-confirm-delete data-form-id="delete-article-{{ $article->id }}" data-object-label="{{ $article->title_uz }}" aria-label="{{ $article->title_uz }} maqolasini o‘chirish"><i class="bi bi-trash" aria-hidden="true"></i></button></div></td></tr>
      @endforeach</tbody></table></div>
      <div class="admin-mobile-list p-3">@foreach($articles as $article)@php $plainText=trim(strip_tags(html_entity_decode((string)$article->description_uz, ENT_QUOTES|ENT_HTML5, 'UTF-8'))); @endphp<article class="admin-mobile-card"><h3 class="h6">{{ $article->title_uz }}</h3><p class="small text-muted">{{ \Illuminate\Support\Str::limit($plainText,100) ?: 'Matn kiritilmagan' }}</p><div class="d-flex justify-content-between align-items-center"><span class="small text-muted">{{ $article->author_name ?: 'Muallif ko‘rsatilmagan' }}</span><div class="admin-actions"><a class="btn btn-outline-primary admin-icon-button" href="{{ route('dashboard.articles.edit',$article) }}" aria-label="{{ $article->title_uz }} maqolasini tahrirlash"><i class="bi bi-pencil" aria-hidden="true"></i></a><button class="btn btn-outline-danger admin-icon-button" type="button" data-confirm-delete data-form-id="delete-article-{{ $article->id }}" data-object-label="{{ $article->title_uz }}" aria-label="{{ $article->title_uz }} maqolasini o‘chirish"><i class="bi bi-trash" aria-hidden="true"></i></button></div></div></article>@endforeach</div>
      <div class="admin-card-body border-top">{{ $articles->links() }}</div>
    @else<x-admin.empty-state icon="newspaper" title="Maqolalar yo‘q" text="Birinchi maqolani qo‘shish uchun yuqoridagi tugmani bosing." />@endif
  </section>
@endsection
