@php $editing = isset($fact) && $fact; $prefix = $editing ? 'fact-'.$fact->id : 'fact-new'; @endphp
<form method="POST" action="{{ $editing ? route('dashboard.company-facts.update', $fact) : route('dashboard.company-facts.store') }}" enctype="multipart/form-data" class="row g-3">@csrf @if($editing) @method('PATCH') @endif
  <div class="col-12"><label class="form-label" for="{{ $prefix }}-key">Kalit <span class="required-mark" aria-hidden="true">*</span></label><input required class="form-control" id="{{ $prefix }}-key" name="key" value="{{ old('key', $editing ? $fact->key : '') }}" placeholder="laboratory"></div>
  @foreach(['uz' => 'Sarlavha (UZ)', 'ru' => 'Заголовок (RU)', 'en' => 'Label (EN)'] as $locale => $label)
    <div class="col-12 col-md-4"><label class="form-label" for="{{ $prefix }}-label-{{ $locale }}">{{ $label }} <span class="required-mark" aria-hidden="true">*</span></label><input required class="form-control" id="{{ $prefix }}-label-{{ $locale }}" name="label_{{ $locale }}" value="{{ old('label_'.$locale, $editing ? $fact->{'label_'.$locale} : '') }}"></div>
  @endforeach
  @foreach(['uz' => 'Qiymat (UZ)', 'ru' => 'Значение (RU)', 'en' => 'Value (EN)'] as $locale => $label)
    <div class="col-12"><label class="form-label" for="{{ $prefix }}-value-{{ $locale }}">{{ $label }} <span class="required-mark" aria-hidden="true">*</span></label><textarea required class="form-control" id="{{ $prefix }}-value-{{ $locale }}" name="value_{{ $locale }}" rows="2">{{ old('value_'.$locale, $editing ? $fact->{'value_'.$locale} : '') }}</textarea></div>
  @endforeach
  <div class="col-12 col-md-6"><label class="form-label" for="{{ $prefix }}-source">Manba URL</label><input class="form-control" id="{{ $prefix }}-source" type="url" name="source_url" value="{{ old('source_url', $editing ? $fact->source_url : '') }}"></div>
  <div class="col-12 col-md-6"><label class="form-label" for="{{ $prefix }}-document">Tasdiqlovchi fayl</label><input class="form-control admin-file-input" id="{{ $prefix }}-document" type="file" name="document" accept=".pdf,image/*" aria-describedby="{{ $prefix }}-document-help"><span class="admin-file-help" id="{{ $prefix }}-document-help">{{ $editing && $fact->document_path ? 'Mavjud fayl saqlanadi; almashtirish uchun yangisini tanlang.' : 'Fayl tanlanmagan.' }}</span></div>
  <div class="col-12"><div class="form-check"><input class="form-check-input" id="{{ $prefix }}-published" type="checkbox" name="is_published" value="1" @checked(old('is_published', $editing ? $fact->is_published : false))><label class="form-check-label" for="{{ $prefix }}-published">Saytda e’lon qilish</label></div></div>
  <div class="col-12 d-flex flex-wrap gap-2"><button class="btn btn-primary" type="submit"><i class="bi bi-check-lg me-1" aria-hidden="true"></i>{{ $editing ? 'Yangilash' : 'Faktni saqlash' }}</button>@if($editing && $fact->document_path)<a class="btn btn-outline-secondary" href="{{ media_url($fact->document_path) }}" target="_blank" rel="noopener"><i class="bi bi-file-earmark-text me-1" aria-hidden="true"></i>Faylni ko‘rish</a>@endif</div>
</form>
