@extends('admin.layouts.app')
@section('title', 'Murojaatlar')

@section('content')
  <header class="admin-page-header"><div><span class="admin-eyebrow"><i class="bi bi-chat-left-dots" aria-hidden="true"></i>Aloqa</span><h1 class="h3 mb-1">Murojaatlar</h1><p>Saytdan kelgan umumiy va kontrakt ishlab chiqarish so‘rovlarini boshqaring.</p></div>@if($newMessageCount)<span class="admin-filter-chip"><i class="bi bi-circle-fill" aria-hidden="true"></i>{{ $newMessageCount }} ta yangi</span>@endif</header>
  <form class="admin-filter-bar mb-4" method="GET" action="{{ route('dashboard.messages.index') }}" aria-label="Murojaat filtrlari"><div class="row g-3 align-items-end"><div class="col-12 col-lg-5"><label class="form-label" for="message-search">Qidiruv</label><input class="form-control" id="message-search" name="q" value="{{ request('q') }}" placeholder="Ism, telefon yoki xabar"></div><div class="col-6 col-lg-2"><label class="form-label" for="message-status">Holati</label><select class="form-select" id="message-status" name="status"><option value="">Barchasi</option><option value="new" @selected(request('status')==='new')>Yangi</option><option value="read" @selected(request('status')==='read')>Ko‘rildi</option><option value="closed" @selected(request('status')==='closed')>Yopildi</option></select></div><div class="col-6 col-lg-2"><label class="form-label" for="message-context">Turi</label><select class="form-select" id="message-context" name="context"><option value="">Barchasi</option><option value="general" @selected(request('context')==='general')>Umumiy</option><option value="manufacturing" @selected(request('context')==='manufacturing')>Ishlab chiqarish</option></select></div><div class="col-12 col-lg-3 d-flex gap-2"><button class="btn btn-primary flex-grow-1">Qidirish</button><a class="btn btn-outline-secondary" href="{{ route('dashboard.messages.index') }}">Tozalash</a></div></div></form>
  <section aria-labelledby="message-list-title"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0" id="message-list-title">Murojaatlar ro‘yxati</h2><span class="text-muted">{{ $messages->total() }} ta natija</span></div>
    @if($messages->count())<div class="row g-3">@foreach($messages as $message)<div class="col-12 col-xl-6"><article class="admin-card h-100 {{ $message->status==='new'?'admin-message-new':'' }}"><div class="admin-card-body"><div class="d-flex justify-content-between gap-3"><div><h3 class="h6 mb-1">{{ $message->name }}</h3>@if($message->company)<div class="small text-muted">{{ $message->company }}</div>@endif</div><div class="text-end"><x-admin.status-badge :status="$message->status" /><div class="small text-muted mt-1">{{ optional($message->created_at)->format('d.m.Y H:i') }}</div></div></div>
      <div class="d-flex flex-wrap gap-2 my-3"><span class="badge text-bg-light">{{ $message->context==='manufacturing'?'Ishlab chiqarish':'Umumiy' }}</span><x-admin.status-badge :status="$message->delivery_status" /></div>
      <dl class="row small mb-3">@if($message->phone)<dt class="col-4">Telefon</dt><dd class="col-8"><a href="tel:{{ $message->phone }}">{{ $message->phone }}</a></dd>@endif @if($message->contact)<dt class="col-4">Aloqa</dt><dd class="col-8">{{ $message->contact }}</dd>@endif @if($message->product_type)<dt class="col-4">Mahsulot turi</dt><dd class="col-8">{{ $message->product_type }}</dd>@endif</dl>
      <p class="mb-3" style="white-space:pre-wrap;overflow-wrap:anywhere">{{ $message->message }}</p><div class="d-flex flex-wrap align-items-end gap-2"><form class="d-flex flex-grow-1 gap-2" method="POST" action="{{ route('dashboard.contact-messages.update',$message) }}">@csrf @method('PATCH')<div class="flex-grow-1"><label class="form-label small" for="message-status-{{ $message->id }}">Murojaat holati</label><select class="form-select" id="message-status-{{ $message->id }}" name="status"><option value="new" @selected($message->status==='new')>Yangi</option><option value="read" @selected($message->status==='read')>Ko‘rildi</option><option value="closed" @selected($message->status==='closed')>Yopildi</option></select></div><button class="btn btn-primary align-self-end" type="submit">Saqlash</button></form><form id="delete-message-{{ $message->id }}" method="POST" action="{{ route('dashboard.contact-messages.destroy',$message) }}">@csrf @method('DELETE')</form><button class="btn btn-outline-danger admin-icon-button" type="button" data-confirm-delete data-form-id="delete-message-{{ $message->id }}" data-object-label="{{ $message->name }} murojaati" aria-label="{{ $message->name }} murojaatini o‘chirish"><i class="bi bi-trash" aria-hidden="true"></i></button></div>
    </div></article></div>@endforeach</div><div class="mt-4">{{ $messages->links() }}</div>@else<x-admin.empty-state class="admin-card" icon="chat-left-text" title="Murojaatlar topilmadi" text="Filtrlarni tozalang yoki yangi murojaat kelishini kuting."><a class="btn btn-outline-primary mt-2" href="{{ route('dashboard.messages.index') }}">Filtrlarni tozalash</a></x-admin.empty-state>@endif
  </section>
@endsection
